/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, DbQueryConnection } from "@prisma/client";

export class DbQueryConnectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.DbQueryConnectionCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.DbQueryConnectionCountArgs>
  ): Promise<number> {
    return this.prisma.dbQueryConnection.count(args);
  }

  async dbQueryConnections<T extends Prisma.DbQueryConnectionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.DbQueryConnectionFindManyArgs>
  ): Promise<DbQueryConnection[]> {
    return this.prisma.dbQueryConnection.findMany(args);
  }
  async dbQueryConnection<T extends Prisma.DbQueryConnectionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DbQueryConnectionFindUniqueArgs>
  ): Promise<DbQueryConnection | null> {
    return this.prisma.dbQueryConnection.findUnique(args);
  }
  async createDbQueryConnection<T extends Prisma.DbQueryConnectionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.DbQueryConnectionCreateArgs>
  ): Promise<DbQueryConnection> {
    return this.prisma.dbQueryConnection.create<T>(args);
  }
  async updateDbQueryConnection<T extends Prisma.DbQueryConnectionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.DbQueryConnectionUpdateArgs>
  ): Promise<DbQueryConnection> {
    return this.prisma.dbQueryConnection.update<T>(args);
  }
  async deleteDbQueryConnection<T extends Prisma.DbQueryConnectionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.DbQueryConnectionDeleteArgs>
  ): Promise<DbQueryConnection> {
    return this.prisma.dbQueryConnection.delete(args);
  }
}
