/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MappingVarianceService } from "../mappingVariance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MappingVarianceCreateInput } from "./MappingVarianceCreateInput";
import { MappingVariance } from "./MappingVariance";
import { MappingVarianceFindManyArgs } from "./MappingVarianceFindManyArgs";
import { MappingVarianceWhereUniqueInput } from "./MappingVarianceWhereUniqueInput";
import { MappingVarianceUpdateInput } from "./MappingVarianceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MappingVarianceControllerBase {
  constructor(
    protected readonly service: MappingVarianceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MappingVariance })
  @nestAccessControl.UseRoles({
    resource: "MappingVariance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMappingVariance(
    @common.Body() data: MappingVarianceCreateInput
  ): Promise<MappingVariance> {
    return await this.service.createMappingVariance({
      data: data,
      select: {
        applicationErhId: true,
        createdAt: true,
        erhId: true,
        id: true,
        mappingLogId: true,
        updatedAt: true,
        varianceTypeId: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MappingVariance] })
  @ApiNestedQuery(MappingVarianceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MappingVariance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mappingVariances(
    @common.Req() request: Request
  ): Promise<MappingVariance[]> {
    const args = plainToClass(MappingVarianceFindManyArgs, request.query);
    return this.service.mappingVariances({
      ...args,
      select: {
        applicationErhId: true,
        createdAt: true,
        erhId: true,
        id: true,
        mappingLogId: true,
        updatedAt: true,
        varianceTypeId: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MappingVariance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MappingVariance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mappingVariance(
    @common.Param() params: MappingVarianceWhereUniqueInput
  ): Promise<MappingVariance | null> {
    const result = await this.service.mappingVariance({
      where: params,
      select: {
        applicationErhId: true,
        createdAt: true,
        erhId: true,
        id: true,
        mappingLogId: true,
        updatedAt: true,
        varianceTypeId: true,
        versionId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MappingVariance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MappingVariance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMappingVariance(
    @common.Param() params: MappingVarianceWhereUniqueInput,
    @common.Body() data: MappingVarianceUpdateInput
  ): Promise<MappingVariance | null> {
    try {
      return await this.service.updateMappingVariance({
        where: params,
        data: data,
        select: {
          applicationErhId: true,
          createdAt: true,
          erhId: true,
          id: true,
          mappingLogId: true,
          updatedAt: true,
          varianceTypeId: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MappingVariance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MappingVariance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMappingVariance(
    @common.Param() params: MappingVarianceWhereUniqueInput
  ): Promise<MappingVariance | null> {
    try {
      return await this.service.deleteMappingVariance({
        where: params,
        select: {
          applicationErhId: true,
          createdAt: true,
          erhId: true,
          id: true,
          mappingLogId: true,
          updatedAt: true,
          varianceTypeId: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
