/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ApplicationItemService } from "../applicationItem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApplicationItemCreateInput } from "./ApplicationItemCreateInput";
import { ApplicationItem } from "./ApplicationItem";
import { ApplicationItemFindManyArgs } from "./ApplicationItemFindManyArgs";
import { ApplicationItemWhereUniqueInput } from "./ApplicationItemWhereUniqueInput";
import { ApplicationItemUpdateInput } from "./ApplicationItemUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApplicationItemControllerBase {
  constructor(
    protected readonly service: ApplicationItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ApplicationItem })
  @nestAccessControl.UseRoles({
    resource: "ApplicationItem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createApplicationItem(
    @common.Body() data: ApplicationItemCreateInput
  ): Promise<ApplicationItem> {
    return await this.service.createApplicationItem({
      data: data,
      select: {
        applicationId: true,
        createdAt: true,
        id: true,
        isActive: true,
        isDeleted: true,
        itemId: true,
        name: true,
        parentId: true,
        sourceSystemId: true,
        sourceSystemParentId: true,
        updatedAt: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ApplicationItem] })
  @ApiNestedQuery(ApplicationItemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ApplicationItem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async applicationItems(
    @common.Req() request: Request
  ): Promise<ApplicationItem[]> {
    const args = plainToClass(ApplicationItemFindManyArgs, request.query);
    return this.service.applicationItems({
      ...args,
      select: {
        applicationId: true,
        createdAt: true,
        id: true,
        isActive: true,
        isDeleted: true,
        itemId: true,
        name: true,
        parentId: true,
        sourceSystemId: true,
        sourceSystemParentId: true,
        updatedAt: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ApplicationItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApplicationItem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async applicationItem(
    @common.Param() params: ApplicationItemWhereUniqueInput
  ): Promise<ApplicationItem | null> {
    const result = await this.service.applicationItem({
      where: params,
      select: {
        applicationId: true,
        createdAt: true,
        id: true,
        isActive: true,
        isDeleted: true,
        itemId: true,
        name: true,
        parentId: true,
        sourceSystemId: true,
        sourceSystemParentId: true,
        updatedAt: true,
        versionId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ApplicationItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApplicationItem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateApplicationItem(
    @common.Param() params: ApplicationItemWhereUniqueInput,
    @common.Body() data: ApplicationItemUpdateInput
  ): Promise<ApplicationItem | null> {
    try {
      return await this.service.updateApplicationItem({
        where: params,
        data: data,
        select: {
          applicationId: true,
          createdAt: true,
          id: true,
          isActive: true,
          isDeleted: true,
          itemId: true,
          name: true,
          parentId: true,
          sourceSystemId: true,
          sourceSystemParentId: true,
          updatedAt: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ApplicationItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApplicationItem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteApplicationItem(
    @common.Param() params: ApplicationItemWhereUniqueInput
  ): Promise<ApplicationItem | null> {
    try {
      return await this.service.deleteApplicationItem({
        where: params,
        select: {
          applicationId: true,
          createdAt: true,
          id: true,
          isActive: true,
          isDeleted: true,
          itemId: true,
          name: true,
          parentId: true,
          sourceSystemId: true,
          sourceSystemParentId: true,
          updatedAt: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
