/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LookupService } from "../lookup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LookupCreateInput } from "./LookupCreateInput";
import { Lookup } from "./Lookup";
import { LookupFindManyArgs } from "./LookupFindManyArgs";
import { LookupWhereUniqueInput } from "./LookupWhereUniqueInput";
import { LookupUpdateInput } from "./LookupUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LookupControllerBase {
  constructor(
    protected readonly service: LookupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Lookup })
  @nestAccessControl.UseRoles({
    resource: "Lookup",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLookup(@common.Body() data: LookupCreateInput): Promise<Lookup> {
    return await this.service.createLookup({
      data: data,
      select: {
        altValue1: true,
        altValue2: true,
        category: true,
        context: true,
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        isActive: true,
        isDeleted: true,
        isEditableByTechAdminOnly: true,
        isViewableByTechAdminOnly: true,
        parentId: true,
        sortOrder: true,
        startDate: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Lookup] })
  @ApiNestedQuery(LookupFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Lookup",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lookups(@common.Req() request: Request): Promise<Lookup[]> {
    const args = plainToClass(LookupFindManyArgs, request.query);
    return this.service.lookups({
      ...args,
      select: {
        altValue1: true,
        altValue2: true,
        category: true,
        context: true,
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        isActive: true,
        isDeleted: true,
        isEditableByTechAdminOnly: true,
        isViewableByTechAdminOnly: true,
        parentId: true,
        sortOrder: true,
        startDate: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Lookup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lookup",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lookup(
    @common.Param() params: LookupWhereUniqueInput
  ): Promise<Lookup | null> {
    const result = await this.service.lookup({
      where: params,
      select: {
        altValue1: true,
        altValue2: true,
        category: true,
        context: true,
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        isActive: true,
        isDeleted: true,
        isEditableByTechAdminOnly: true,
        isViewableByTechAdminOnly: true,
        parentId: true,
        sortOrder: true,
        startDate: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Lookup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lookup",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLookup(
    @common.Param() params: LookupWhereUniqueInput,
    @common.Body() data: LookupUpdateInput
  ): Promise<Lookup | null> {
    try {
      return await this.service.updateLookup({
        where: params,
        data: data,
        select: {
          altValue1: true,
          altValue2: true,
          category: true,
          context: true,
          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          isActive: true,
          isDeleted: true,
          isEditableByTechAdminOnly: true,
          isViewableByTechAdminOnly: true,
          parentId: true,
          sortOrder: true,
          startDate: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Lookup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lookup",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLookup(
    @common.Param() params: LookupWhereUniqueInput
  ): Promise<Lookup | null> {
    try {
      return await this.service.deleteLookup({
        where: params,
        select: {
          altValue1: true,
          altValue2: true,
          category: true,
          context: true,
          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          isActive: true,
          isDeleted: true,
          isEditableByTechAdminOnly: true,
          isViewableByTechAdminOnly: true,
          parentId: true,
          sortOrder: true,
          startDate: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
