/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MappingLogService } from "../mappingLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MappingLogCreateInput } from "./MappingLogCreateInput";
import { MappingLog } from "./MappingLog";
import { MappingLogFindManyArgs } from "./MappingLogFindManyArgs";
import { MappingLogWhereUniqueInput } from "./MappingLogWhereUniqueInput";
import { MappingLogUpdateInput } from "./MappingLogUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MappingLogControllerBase {
  constructor(
    protected readonly service: MappingLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MappingLog })
  @nestAccessControl.UseRoles({
    resource: "MappingLog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMappingLog(
    @common.Body() data: MappingLogCreateInput
  ): Promise<MappingLog> {
    return await this.service.createMappingLog({
      data: data,
      select: {
        applicationId: true,
        applicationMappedRecordCount: true,
        applicationRecordCount: true,
        applicationUnmappedRecordCount: true,
        createdAt: true,
        deletedMappingsRecordCount: true,
        id: true,
        mappedRecordCount: true,
        newMappingRecordCount: true,
        recordCount: true,
        statusId: true,
        unmappedRecordCount: true,
        updatedAt: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MappingLog] })
  @ApiNestedQuery(MappingLogFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MappingLog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mappingLogs(@common.Req() request: Request): Promise<MappingLog[]> {
    const args = plainToClass(MappingLogFindManyArgs, request.query);
    return this.service.mappingLogs({
      ...args,
      select: {
        applicationId: true,
        applicationMappedRecordCount: true,
        applicationRecordCount: true,
        applicationUnmappedRecordCount: true,
        createdAt: true,
        deletedMappingsRecordCount: true,
        id: true,
        mappedRecordCount: true,
        newMappingRecordCount: true,
        recordCount: true,
        statusId: true,
        unmappedRecordCount: true,
        updatedAt: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MappingLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MappingLog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mappingLog(
    @common.Param() params: MappingLogWhereUniqueInput
  ): Promise<MappingLog | null> {
    const result = await this.service.mappingLog({
      where: params,
      select: {
        applicationId: true,
        applicationMappedRecordCount: true,
        applicationRecordCount: true,
        applicationUnmappedRecordCount: true,
        createdAt: true,
        deletedMappingsRecordCount: true,
        id: true,
        mappedRecordCount: true,
        newMappingRecordCount: true,
        recordCount: true,
        statusId: true,
        unmappedRecordCount: true,
        updatedAt: true,
        versionId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MappingLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MappingLog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMappingLog(
    @common.Param() params: MappingLogWhereUniqueInput,
    @common.Body() data: MappingLogUpdateInput
  ): Promise<MappingLog | null> {
    try {
      return await this.service.updateMappingLog({
        where: params,
        data: data,
        select: {
          applicationId: true,
          applicationMappedRecordCount: true,
          applicationRecordCount: true,
          applicationUnmappedRecordCount: true,
          createdAt: true,
          deletedMappingsRecordCount: true,
          id: true,
          mappedRecordCount: true,
          newMappingRecordCount: true,
          recordCount: true,
          statusId: true,
          unmappedRecordCount: true,
          updatedAt: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MappingLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MappingLog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMappingLog(
    @common.Param() params: MappingLogWhereUniqueInput
  ): Promise<MappingLog | null> {
    try {
      return await this.service.deleteMappingLog({
        where: params,
        select: {
          applicationId: true,
          applicationMappedRecordCount: true,
          applicationRecordCount: true,
          applicationUnmappedRecordCount: true,
          createdAt: true,
          deletedMappingsRecordCount: true,
          id: true,
          mappedRecordCount: true,
          newMappingRecordCount: true,
          recordCount: true,
          statusId: true,
          unmappedRecordCount: true,
          updatedAt: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
