/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ErhService } from "../erh.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ErhCreateInput } from "./ErhCreateInput";
import { Erh } from "./Erh";
import { ErhFindManyArgs } from "./ErhFindManyArgs";
import { ErhWhereUniqueInput } from "./ErhWhereUniqueInput";
import { ErhUpdateInput } from "./ErhUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ErhControllerBase {
  constructor(
    protected readonly service: ErhService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Erh })
  @nestAccessControl.UseRoles({
    resource: "Erh",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createErh(@common.Body() data: ErhCreateInput): Promise<Erh> {
    return await this.service.createErh({
      data: data,
      select: {
        createdAt: true,
        id: true,
        isActive: true,
        isDeleted: true,
        level1Id: true,
        level1VersionId: true,
        name: true,
        parentId: true,
        parentVersionId: true,
        updatedAt: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Erh] })
  @ApiNestedQuery(ErhFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Erh",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async erhs(@common.Req() request: Request): Promise<Erh[]> {
    const args = plainToClass(ErhFindManyArgs, request.query);
    return this.service.erhs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isActive: true,
        isDeleted: true,
        level1Id: true,
        level1VersionId: true,
        name: true,
        parentId: true,
        parentVersionId: true,
        updatedAt: true,
        versionId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Erh })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Erh",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async erh(@common.Param() params: ErhWhereUniqueInput): Promise<Erh | null> {
    const result = await this.service.erh({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isActive: true,
        isDeleted: true,
        level1Id: true,
        level1VersionId: true,
        name: true,
        parentId: true,
        parentVersionId: true,
        updatedAt: true,
        versionId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Erh })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Erh",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateErh(
    @common.Param() params: ErhWhereUniqueInput,
    @common.Body() data: ErhUpdateInput
  ): Promise<Erh | null> {
    try {
      return await this.service.updateErh({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          isActive: true,
          isDeleted: true,
          level1Id: true,
          level1VersionId: true,
          name: true,
          parentId: true,
          parentVersionId: true,
          updatedAt: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Erh })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Erh",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteErh(
    @common.Param() params: ErhWhereUniqueInput
  ): Promise<Erh | null> {
    try {
      return await this.service.deleteErh({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isActive: true,
          isDeleted: true,
          level1Id: true,
          level1VersionId: true,
          name: true,
          parentId: true,
          parentVersionId: true,
          updatedAt: true,
          versionId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
